run:
    skip-dirs:
        - .gen
        - client

linters-settings:
    golint:
        min-confidence: 0.9

    gocyclo:
        min-complexity: 20

    lll:
        line-length: 200

    goimports:
        local-prefixes: github.com/sagikazarmark/modern-go-application

linters:
    enable-all: true
    disable:
        - gocritic

