version: 2.1

orbs:
    helm: banzaicloud/helm@0.0.3
    docker: circleci/docker@0.5.14


executors:
    docker:
        docker:
            -
                image: circleci/golang:1.12
                environment:
                    GOFLAGS: -mod=readonly

commands:
    restore_build_cache:
        description: Restore build cache
        steps:
            -
                restore_cache:
                    name: Restore build dependencies
                    keys:
                        - build-deps-v1-{{ .Branch }}-{{ checksum "Makefile" }}

    restore_go_module_cache:
        description: Restore Go module cache
        steps:
            -
                restore_cache:
                    name: Restore Go module cache
                    keys:
                        - gomod-v1-{{ .Branch }}-{{ checksum "go.sum" }}
                        - gomod-v1-{{ .Branch }}
                        - gomod-v1-master
                        - gomod-v1

    docker-publish-latest:
        parameters:
            registry:
                default: docker.io
                description: Name of registry to use, defaults to docker.io
                type: string
            image:
                description: Name of image to tag as latest
                type: string
            tag:
                default: $CIRCLE_TAG
                description: Image tag, defaults to the value of $CIRCLE_TAG
                type: string
            version_pattern:
                default: '^[0-9]+\.[0-9]+\.[0-9]+$'
                description: Publish latest only for tags matching this pattern
                type: string
        steps:
            - run:
                name: Publish latest docker image
                command: |
                    if echo "<<parameters.tag>>" | grep -Eq '<<parameters.version_pattern>>'; then
                      docker tag <<parameters.image>>:<<parameters.tag>> <<parameters.registry>>/<<parameters.image>>:latest
                      docker push <<parameters.registry>>/<<parameters.image>>:latest
                    else
                      echo 'Unstable version. Skip publishing latest.'
                    fi

jobs:
    dependencies:
        executor: docker

        steps:
            - checkout
            - restore_go_module_cache

            -
                run:
                    name: Download Go module cache
                    command: go mod download

            -
                run:
                    name: Install build dependencies
                    command: make -j bin/golangci-lint bin/licensei bin/gotestsum

            -
                save_cache:
                    name: Save Go module cache
                    key: gomod-v1-{{ .Branch }}-{{ checksum "go.sum" }}
                    paths:
                        - /go/pkg/mod

            -
                save_cache:
                    name: Save build dependencies
                    key: build-deps-v1-{{ .Branch }}-{{ checksum "Makefile" }}
                    paths:
                        - bin/

    static-checks:
        executor: docker

        steps:
            - checkout
            - restore_build_cache
            - restore_go_module_cache

            -
                restore_cache:
                    name: Restore license cache
                    keys:
                        - licensei-v1-{{ .Branch }}-{{ checksum "go.sum" }}
                        - licensei-v1-{{ .Branch }}
                        - licensei-v1-master
                        - licensei-v1

            -
                run:
                    name: Download license information for dependencies
                    command: make license-cache

            -
                save_cache:
                    name: Save license cache
                    key: licensei-v1-{{ .Branch }}-{{ checksum "go.sum" }}
                    paths:
                        - .licensei.cache

            -
                run:
                    name: Check dependency licenses
                    command: make license-check

            -
                run:
                    name: Run linter
                    command: make lint

    build:
        executor: docker

        steps:
            - checkout
            - restore_build_cache
            - restore_go_module_cache

            -
                run:
                    name: Build
                    command: make build

    unit-tests:
        executor: docker

        steps:
            - checkout
            - restore_build_cache
            - restore_go_module_cache

            -
                run:
                    name: Run tests
                    command: TEST_PKGS=$(echo `go list ./... | circleci tests split`) TEST_REPORT_NAME=results_${CIRCLE_NODE_INDEX}.xml make test

            -
                store_test_results:
                    path: build/test_results/

workflows:
    version: 2
    ci:
        jobs:
            - dependencies
            - static-checks:
                  requires:
                      - dependencies
            - build:
                  requires:
                      - dependencies
            - unit-tests:
                  requires:
                      - dependencies
            - docker/publish:
                  name: Build docker image
                  deploy: false
                  image: banzaicloud/telescopes
                  tag: $CIRCLE_BRANCH
                  filters:
                      branches:
                          ignore: master
            - docker/publish:
                  name: Publish master docker image
                  context: dockerhub
                  deploy: true
                  image: banzaicloud/telescopes
                  tag: master
                  requires:
                      - build
                      - static-checks
                      - unit-tests
                  filters:
                      branches:
                          only: master
            - docker/publish:
                  name: Publish tagged & latest docker image
                  context: dockerhub
                  image: banzaicloud/telescopes
                  tag: $CIRCLE_TAG
                  filters:
                      tags:
                          only: /^[0-9]+\.[0-9]+\.[0-9]+(?:-(?:dev|rc)\.[0-9]+)?$/
                      branches:
                          ignore: /.*/
                  after_build:
                      - docker-publish-latest:
                          image: banzaicloud/telescopes
                          tag: $CIRCLE_TAG

    helm-chart:
        jobs:
            - helm/lint-chart:
                  chart-path: charts/telescopes
                  filters:
                      tags:
                          ignore: /.*/

            - helm/publish-chart:
                  context: helm
                  chart-path: charts/telescopes
                  filters:
                      branches:
                          ignore: /.*/
                      tags:
                          only: /chart\/telescopes\/\d+.\d+.\d+/
